import fs from 'node:fs/promises';
import path from 'node:path';
import ExcelJS from 'exceljs';

if (!process.argv[2]) throw new Error('Usage: node scripts/generateSeed.mjs <source.xlsx> [output.js]');
const sourcePath = path.resolve(process.argv[2]);
const outputPath = path.resolve(process.argv[3] || 'src/data/seed.js');

const phases = [
  { key: 'requirement', name: 'Requirement Phase', short: 'RP', acronym: 'RP', description: 'ICP and workload analysis.' },
  { key: 'development', name: 'Development Phase', short: 'DP', acronym: 'DP', description: 'Design, fabrication, integration, and technical development.' },
  { key: 'acquisition', name: 'Acquisition Phase', short: 'AP', acronym: 'AP', description: 'Purchasing activity after contract award.' },
  { key: 'operation-sustainment', name: 'Operation and Sustainment Phase', short: 'O&S', acronym: 'O&S', description: 'Transition following PMSD and METBUL publication.' },
  { key: 'production-procurement', name: 'Production/Procurement Phase', short: 'PP', acronym: 'PP', description: 'Bid testing or procurement of multiple parts.' },
];

const glossary = [
  ['RP', 'Requirement Phase', 'ICP and workload analysis.'],
  ['DP', 'Development Phase', 'Future project work involving design, fabrication, or integration.'],
  ['AP', 'Acquisition Phase', 'Purchasing period immediately after contracts are awarded.'],
  ['O&S', 'Operation and Sustainment Phase', 'Follows PMSD and METBUL publication.'],
  ['PP', 'Production/Procurement Phase', 'Applicable to bid testing or procurement of multiple parts.'],
  ['CSS', 'Calibration Standard Specification', 'Specifies technical details for replacement calibration standards.'],
  ['MTR', 'Measurement Technology Report', 'Final internal report or summary before a project moves to acquisition.'],
  ['RFI', 'Request for Information', 'Publicizes specifications so vendors can respond.'],
  ['RFP', 'Request for Procurement', 'Procurement request associated with CSS development.'],
  ['COT', 'Commercial off the Shelf', 'Products widely available for purchase.'],
  ['ATP', 'Acceptance Test Plan', 'Test plan developed for a potential replacement-standard candidate.'],
  ['PMSD', 'Primary Measurement Standard Document', 'Procedure developed specifically for primary measurement systems.'],
  ['PFA', 'Probability False Acceptance', 'Calculated through TUR using method 4; PFA cannot exceed 2%.'],
  ['PFR', 'Probability False Rejection', 'Cannot exceed 15%.'],
  ['PO', 'Program Office', 'NAVAIR METCAL Program Office.'],
  ['SOW', 'Statement of Work', 'Detailed documentation or contract of vendor deliverables.'],
  ['PTB', 'Physikalisch-Technische Bundesanstalt', 'Germany\'s national metrology institute.'],
  ['NIMS', 'National Incident Management System', 'Metrology product used to research ICP history, COG, and initial actions.'],
  ['BT', 'Bench Test', 'Bench test supporting PMSD and ICP work.'],
  ['Milestone A', '—', 'ICPs that support 50% of workload hours.'],
  ['Milestone B', '—', 'ICPs supporting 50% to 90% of workload hours remaining from Milestone A.'],
  ['Milestone C', '—', 'Remaining ICPs supporting the bottom 10% of workload hours.'],
  ['RFQ', 'Request for Quality Assurance', 'Alternative term sometimes used for RFP.'],
  ['CSMBOD', 'Calibration Standard Modernization Board of Directors', 'The modernization program office and leadership board.'],
  ['CERAP', 'Calibration Equipment Requirement Analysis Program', 'Requirement-analysis tool for models, hours, customers, ICPs, and standards data.'],
  ['MEASURE', 'Metrology Automated System for Uniform Recall and Reporting', 'Standards inventory and calibration-record inquiry system.'],
  ['LIS', 'Integrated Logistic Support', 'Post-documentation development for an acquired measurement standard.'],
  ['MR', 'Market Research', 'Initial research for COT or R&D replacement-standard candidates.'],
  ['TEMP', 'Test and Evaluation Master Plan', 'Test planning comparable to an Acceptance Test Plan.'],
  ['CDRL', 'Contract Data Requirement List', 'Post-award requirements such as unit, ancillary-item, or software-update deliverables.'],
  ['LRIP', 'Low Rate Initial Production', 'Used for fleet/depot efforts when multiple systems are needed.'],
  ['QVI', 'Quality Validation Inspection', 'Report generated by modernization engineers after product arrival.'],
  ['ADPG', 'Automated Deadweight Piston Gauge', 'New pressure standard project.'],
  ['Days (IW)', 'In-work', 'Term that may include weekends in addition to business days.'],
  ['KPP', 'Key Performance Requirement', 'Critical contributors used to improve quality, uncertainty, and efficiency.'],
  ['NDA', 'Non-Disclosure Agreement', 'Coordinate with the legal office before signing during vendor evaluation.'],
  ['TTM', 'Task Team Manager', 'Task-team management term.'],
].map(([acronym, term, definition]) => ({ acronym, term, definition }));

const taskTemplate = [
  ['RP-01', 'Complete ICP and workload analysis', 'requirement'],
  ['DP-01', 'Complete design, development, and technical documentation', 'development'],
  ['AP-01', 'Complete acquisition and contract-award activities', 'acquisition'],
  ['OS-01', 'Publish PMSD/METBUL and transition to sustainment', 'operation-sustainment'],
  ['PP-01', 'Complete production/procurement and acceptance testing', 'production-procurement'],
];

const slug = (value) => String(value || '').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
const isoDate = (value) => value instanceof Date && !Number.isNaN(value.valueOf()) ? value.toISOString().slice(0, 10) : '';

function inferPhase(text) {
  const value = String(text || '').toLowerCase();
  if (/not yet started|requirement phase|\bicp\b|workload/.test(value)) return 'requirement';
  if (/pmsd|metbul|delivery|delivered, awaiting|training and installation|on-hold until/.test(value)) return 'operation-sustainment';
  if (/acceptance completed|testing for delivered|delivered parts|bid test|\bparts\b/.test(value)) return 'production-procurement';
  if (/in contract|procurement|acquisition|quote finalized|list submitted|funding|purchas/.test(value)) return 'acquisition';
  if (/css|design|work in progress|working with nist|required uncertainty|procedure|support procedure|web app|alpha testing|spinning rotor/.test(value)) return 'development';
  return 'requirement';
}

function projectStatus(text) {
  if (/not yet started/i.test(text)) return 'Planned';
  if (/hold|on-hold/i.test(text)) return 'On Hold';
  return 'In Progress';
}

const workbook = new ExcelJS.Workbook();
await workbook.xlsx.readFile(sourcePath);
const sheet = workbook.getWorksheet('Mod Projects') || workbook.worksheets[0];
if (!sheet) throw new Error('The workbook contains no worksheets.');

const sectionRows = new Map([[2, 'Electrical'], [16, 'Mechanical'], [33, 'Fleet / Depot']]);
let section = '';
const sourceRows = [];
sheet.eachRow({ includeEmpty: true }, (row, rowNumber) => {
  if (sectionRows.has(rowNumber)) section = sectionRows.get(rowNumber);
  const title = row.getCell(2).value;
  const trackingId = row.getCell(3).value;
  if (!title || !trackingId || !section || !/^FY/i.test(String(trackingId))) return;
  sourceRows.push({
    title: String(title).trim(),
    trackingId: String(trackingId).trim(),
    section,
    ownerName: String(row.getCell(4).value || 'Unassigned').trim(),
    currentStatus: String(row.getCell(5).value || '').trim(),
    actionItem: String(row.getCell(6).value || '').trim(),
    actionee: String(row.getCell(7).value || '').trim(),
    targetFinish: isoDate(row.getCell(8).value),
    sourceTargetLabel: typeof row.getCell(8).value === 'string' ? row.getCell(8).value.trim() : '',
    sourceRisk: String(row.getCell(9).value || '').trim(),
  });
});

const ownerAliases = new Map();
const roleCounts = new Map();
const rolePrefix = (section) => section === 'Fleet / Depot' ? 'Fleet Engineer' : `${section} Engineer`;
const nextRole = (prefix) => {
  const count = (roleCounts.get(prefix) || 0) + 1;
  roleCounts.set(prefix, count);
  return `${prefix} ${String.fromCharCode(64 + count)}`;
};
for (const row of sourceRows) {
  if (row.ownerName && row.ownerName !== 'Unassigned' && !ownerAliases.has(row.ownerName)) ownerAliases.set(row.ownerName, nextRole(rolePrefix(row.section)));
}
for (const row of sourceRows) {
  for (const name of row.actionee.split(',').map((value) => value.trim()).filter(Boolean)) {
    if (!ownerAliases.has(name)) ownerAliases.set(name, nextRole('Project Support'));
  }
}
const sanitizeOwners = (value) => {
  const raw = String(value || '').trim();
  if (!raw || raw === 'Unassigned') return raw;
  return raw.split(',').map((name) => ownerAliases.get(name.trim()) || 'Project Team').join(', ');
};
const sectionCounts = new Map();
sourceRows.forEach((row) => {
  const sectionCount = (sectionCounts.get(row.section) || 0) + 1;
  sectionCounts.set(row.section, sectionCount);
  const sectionCode = row.section === 'Electrical' ? 'E' : row.section === 'Mechanical' ? 'M' : 'FD';
  row.stageKey = inferPhase(row.currentStatus);
  row.status = projectStatus(row.currentStatus);
  row.hasAction = !!row.actionItem;
  row.title = `${row.section === 'Fleet / Depot' ? 'Fleet & Depot' : row.section} Modernization ${String(sectionCount).padStart(2, '0')}`;
  row.trackingId = `MOCK-${sectionCode}-${String(sectionCount).padStart(3, '0')}`;
  row.ownerName = sanitizeOwners(row.ownerName) || 'Unassigned';
  row.actionee = sanitizeOwners(row.actionee);
  row.currentStatus = row.status === 'On Hold'
    ? `Schedule hold in ${phases.find((phase) => phase.key === row.stageKey).name}.`
    : row.status === 'Planned'
      ? 'Project is ready to begin requirement analysis.'
      : `${phases.find((phase) => phase.key === row.stageKey).name} work is in progress.`;
  row.actionItem = row.hasAction ? `Complete the next ${phases.find((phase) => phase.key === row.stageKey).short} project action.` : '';
});

const projects = [];
const tasks = [];
const updates = [];

sourceRows.forEach((row, projectIndex) => {
  const projectKey = `${slug(row.trackingId)}-${slug(row.title)}`;
  const stageKey = row.stageKey;
  const stageIndex = phases.findIndex((phase) => phase.key === stageKey);
  const status = row.status;
  const projectTasks = taskTemplate.map(([wbs, title, phaseKey], taskIndex) => {
    const taskPhaseIndex = phases.findIndex((phase) => phase.key === phaseKey);
    const isPrior = taskPhaseIndex < stageIndex;
    const isCurrent = taskPhaseIndex === stageIndex;
    return {
      id: `${projectKey}-${slug(wbs)}`,
      projectKey,
      wbs,
      title,
      phaseKey,
      order: taskIndex + 1,
      status: isPrior ? 'Complete' : isCurrent && status === 'On Hold' ? 'Blocked' : isCurrent && status !== 'Planned' ? 'In Progress' : 'Not Started',
      startDate: '',
      finishDate: isPrior ? '2026-08-31' : '',
      dueDate: isCurrent ? row.targetFinish : '',
      ownerName: row.ownerName,
      ownerEmail: '',
      ownerKey: '',
      notes: isCurrent ? row.currentStatus : '',
      blockedReason: isCurrent && status === 'On Hold' ? row.currentStatus : '',
      sourceStartLabel: '',
      dataIssue: '',
    };
  });

  if (row.actionItem) {
    projectTasks.push({
      id: `${projectKey}-action`,
      projectKey,
      wbs: `${phases[stageIndex].short.replace(/[^A-Z]/g, '')}-A1`,
      title: row.actionItem,
      phaseKey: stageKey,
      order: stageIndex + 1.5,
      status: status === 'On Hold' ? 'Blocked' : 'In Progress',
      startDate: '',
      finishDate: '',
      dueDate: row.targetFinish,
      ownerName: row.actionee || row.ownerName,
      ownerEmail: '',
      ownerKey: '',
      notes: `Source action item from the August 2026 portfolio review.${row.sourceTargetLabel ? ` ECD: ${row.sourceTargetLabel}.` : ''}`,
      blockedReason: status === 'On Hold' ? row.currentStatus : '',
      sourceStartLabel: '',
      dataIssue: '',
    });
  }

  projectTasks.sort((a, b) => a.order - b.order).forEach((task, index) => { task.order = index + 1; });
  tasks.push(...projectTasks);
  const completeCount = projectTasks.filter((task) => task.status === 'Complete').length;
  projects.push({
    id: `project-${String(projectIndex + 1).padStart(2, '0')}`,
    projectKey,
    title: row.title,
    measurementArea: row.section,
    trackingId: row.trackingId,
    description: row.currentStatus || `${row.section} modernization project.`,
    ownerName: row.ownerName,
    ownerEmail: '',
    ownerKey: '',
    managerName: 'Unassigned',
    managerEmail: '',
    priority: 'Medium',
    health: /on target/i.test(row.sourceRisk) ? 'On Track' : status === 'On Hold' ? 'At Risk' : 'Needs Review',
    status,
    currentStageKey: stageKey,
    percentComplete: Math.round((completeCount / projectTasks.length) * 100),
    targetFinish: row.targetFinish,
    nextMilestone: row.actionItem || phases[stageIndex].description,
    nextMilestoneDate: row.targetFinish,
    sourceNotes: [row.currentStatus && `Status: ${row.currentStatus}`, row.sourceRisk && `Risk: ${row.sourceRisk}`, row.sourceTargetLabel && `ECD: ${row.sourceTargetLabel}`].filter(Boolean).join(' • '),
    importedBaseline: true,
    dataIssueCount: 0,
    tags: [row.section, row.trackingId],
  });
  updates.push({
    id: `${projectKey}-review-update`,
    projectKey,
    type: 'Status',
    summary: row.currentStatus || 'No status narrative was provided in the source review.',
    entryDate: '2026-08-31',
    authorName: 'August portfolio review',
    authorEmail: '',
    authorKey: '',
  });
});

const seed = {
  source: 'August 2026 modernization review workbook',
  importedAt: '2026-08-31',
  phases,
  glossary,
  projects,
  tasks,
  updates,
  risks: [],
};
const contents = `// Generated mock visualization data. Do not edit by hand.\nexport const seedData = ${JSON.stringify(seed, null, 2)};\n`;
await fs.mkdir(path.dirname(outputPath), { recursive: true });
await fs.writeFile(outputPath, contents, 'utf8');
console.log(JSON.stringify({ projects: projects.length, tasks: tasks.length, glossary: glossary.length, outputPath }, null, 2));
